-- Conéctate como administrador (como SYS o un usuario con privilegios de DBA)

-- Creación de tablas para la base de datos de una red social
CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    contrasena VARCHAR2(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    foto_perfil VARCHAR2(255)
);

CREATE TABLE Publicaciones (
    id_publicacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    contenido CLOB NOT NULL,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_publicacion FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

CREATE TABLE Comentarios (
    id_comentario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publicacion NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    comentario CLOB NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_publicacion_comentario FOREIGN KEY (id_publicacion) REFERENCES Publicaciones(id_publicacion),
    CONSTRAINT fk_usuario_comentario FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

CREATE TABLE Relaciones (
    id_usuario1 NUMBER NOT NULL,
    id_usuario2 NUMBER NOT NULL,
    fecha_amistad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_usuario1, id_usuario2),
    CONSTRAINT fk_usuario1 FOREIGN KEY (id_usuario1) REFERENCES Usuarios(id_usuario),
    CONSTRAINT fk_usuario2 FOREIGN KEY (id_usuario2) REFERENCES Usuarios(id_usuario)
);

CREATE TABLE Mensajes (
    id_mensaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_emisor NUMBER NOT NULL,
    id_usuario_receptor NUMBER NOT NULL,
    mensaje CLOB NOT NULL,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emisor FOREIGN KEY (id_usuario_emisor) REFERENCES Usuarios(id_usuario),
    CONSTRAINT fk_receptor FOREIGN KEY (id_usuario_receptor) REFERENCES Usuarios(id_usuario)
);

-- Creación de un nuevo usuario para administrar la tabla Publicaciones
CREATE USER usuario_nuevo IDENTIFIED BY contraseña_segura;

-- Asignación de permisos
GRANT ALL PRIVILEGES ON Publicaciones TO usuario_nuevo;
